### ISSUE TITLE
Object footprint in heap is not realistic using RealAllocator

### ISSUE THREAD

**Issue by aarontabor** [GarCoSim/TraceFileSim#3]
The purpose of the `RealAllocator` is to simulate a realistic memory footprint in the heap. Currently, the heap is not being represented accurately. In addition to the size specified in the tracefile line, an additional `sizeof(Object)` bytes are being allocated so that the C++ Object can fit in heap. This leads to larger heap, more collections, and inaccurate analysis of localization and cache performance.

An object in our simulated heap should instead be represented as it would be in a real JVM. The object should have a header (which includes a pointer to the object's Class) and the fields associated with the object. In our case, these fields include pointers to other objects.

**Comment by tmbasa** [comment]
I fixed this in commit e9608dc3931623348ecbc0fc58ea29dddc601d7c

**Comment by tmbasa** [comment]
As of commit e9608dc3931623348ecbc0fc58ea29dddc601d7c, object pointer fields are now stored within the space allocated for an object in heap

**Comment by aarontabor** [comment]
@mazder Throughout the code base, the trace line attribute identified by `S` is being referred to as the objects 'payload' size, even though this is the total amount of memory being allocated for the object.

Just to confirm, the trace line attribute `S` represents the size of the entire java object (i.e. header + payload = S), correct?

**Comment by konsna** [comment]
This is correct. It was introduced during the development of the real allocater, but should be changed. There should be 2 functions. One returning the payload size and another returning the actual object size on the heap.

**Comment by mazder** [comment]
Yes, S is the size of an object, in bytes, including the header taking into account object alignment and minimum object size. (From JVM)

**Comment by aarontabor** [comment]
Okay, thanks. I'll make sure that the `Object` class has 2 functions: 
- `Object::getHeapSize()`
- `Object::getPayloadSize()`

**Comment by konsna** [comment]
@aarontabor Perfect!

Just make sure the allocators use the correct one.

**Comment by mazder** [comment]
Aron,  please see my email for further clarification S in trace file.

**Comment by aarontabor** [comment]
this has been addressed in e2de04d4e91fb7a8b7b7dcd1e5d5354b5c7c4769
